package Acme::CPANLists::Import::PerlAdvent::2008_12_11;

# DATE
# VERSION

our @Module_Lists = ({description=>"This list is generated by extracting module names mentioned in [http://perladvent.org/2008/11/] (retrieved on 2016-11-07). Visit the URL for the full contents.",entries=>[{module=>"Module::ScanDeps"}],summary=>"Modules mentioned in Perl Advent Calendar 2008 (day 11)"});

1;
# ABSTRACT: Modules mentioned in Perl Advent Calendar 2008 (day 11)

=head1 DESCRIPTION

This module is generated by extracting module names mentioned in L<http://perladvent.org/2008/11/> (retrieved on 2016-11-07). Visit the URL for the full contents.

