package Acme::CPANLists::Import::PerlAdvent::2008_12_23;

# DATE
# VERSION

our @Module_Lists = ({description=>"This list is generated by extracting module names mentioned in [http://perladvent.org/2008/23/] (retrieved on 2016-11-07). Visit the URL for the full contents.",entries=>[{module=>"Test::Perl::Critic::Progressive"}],summary=>"Modules mentioned in Perl Advent Calendar 2008 (day 23)"});

1;
# ABSTRACT: Modules mentioned in Perl Advent Calendar 2008 (day 23)

=head1 DESCRIPTION

This module is generated by extracting module names mentioned in L<http://perladvent.org/2008/23/> (retrieved on 2016-11-07). Visit the URL for the full contents.

