package Acme::CPANLists::Import::PerlAdvent::2008_12_05;

# DATE
# VERSION

our @Module_Lists = ({description=>"This list is generated by extracting module names mentioned in [http://perladvent.org/2008/5/] (retrieved on 2016-11-07). Visit the URL for the full contents.",entries=>[{module=>"Test::Group"},{module=>"Test::Harness"}],summary=>"Modules mentioned in Perl Advent Calendar 2008 (day 5)"});

1;
# ABSTRACT: Modules mentioned in Perl Advent Calendar 2008 (day 5)

=head1 DESCRIPTION

This module is generated by extracting module names mentioned in L<http://perladvent.org/2008/5/> (retrieved on 2016-11-07). Visit the URL for the full contents.

