package Acme::CPANLists::Import::PerlAdvent::2008;

# DATE
# VERSION

our @Module_Lists = ({description=>"This list is generated by extracting module names mentioned in [http://perladvent.org/2008/] (retrieved on 2016-11-07). Visit the URL for the full contents.",entries=>[{module=>"ToolSet"},{module=>"List::Search"},{module=>"Math::Prime::TiedArray"},{module=>"Math::BigApprox"},{module=>"Lingua::Ident"},{module=>"Test::Group"},{module=>"Test::Harness"},{module=>"Sub::Curry"},{module=>"IPC::Filter"},{module=>"Bundle::ToolSet"},{module=>"Module::ScanDeps"},{module=>"Tk"},{module=>"Text::Aspell"},{module=>"Text::SpellChecker"},{module=>"Lingua::Translate"},{module=>"Lingua::Translate::Google"},{module=>"Lingua::Translate::InterTran"},{module=>"SelfLoader"},{module=>"Config::General"},{module=>"String::Approx"},{module=>"Text::Metaphone"},{module=>"Tie::OneOff"},{module=>"Regexp::Subst::Parallel"},{module=>"Test::Perl::Critic::Progressive"},{module=>"Sort::ByExample"},{module=>"Sort::Half::Maker"}],summary=>"Modules mentioned in Perl Advent Calendar 2008"});

1;
# ABSTRACT: Modules mentioned in Perl Advent Calendar 2008

=head1 DESCRIPTION

This module is generated by extracting module names mentioned in L<http://perladvent.org/2008/> (retrieved on 2016-11-07). Visit the URL for the full contents.

