#!/usr/bin/env perl

use 5.010;
use strict;
use warnings;
use FindBin '$Bin';

use App::CreateAcmeCPANListsImportModules;
use Perinci::Sub::Util qw(gen_curried_sub);
use Perinci::CmdLine::Any;

gen_curried_sub(
    'App::CreateAcmeCPANListsImportModules::create_acme_cpanlists_import_modules',
    {
        modules => [
            {
                name => '2008',
                url => "http://perladvent.org/2008/",
                extract_urls => [map {"http://perladvent.org/2008/$_/"}
                                     1..6,8,10..16,18,20..24],
                summary => 'Modules mentioned in Perl Advent Calendar 2008',
            },
            {
                name => '2008_12_01',
                summary => "Modules mentioned in Perl Advent Calendar 2008 (day 1)",
                url => "http://perladvent.org/2008/1/",
            },
            {
                name => '2008_12_02',
                summary => "Modules mentioned in Perl Advent Calendar 2008 (day 2)",
                url => "http://perladvent.org/2008/2/",
            },
            {
                name => '2008_12_03',
                summary => "Modules mentioned in Perl Advent Calendar 2008 (day 3)",
                url => "http://perladvent.org/2008/3/",
            },
            {
                name => '2008_12_04',
                summary => "Modules mentioned in Perl Advent Calendar 2008 (day 4)",
                url => "http://perladvent.org/2008/4/",
            },
            {
                name => '2008_12_05',
                summary => "Modules mentioned in Perl Advent Calendar 2008 (day 5)",
                url => "http://perladvent.org/2008/5/",
            },
            {
                name => '2008_12_06',
                summary => "Modules mentioned in Perl Advent Calendar 2008 (day 6)",
                url => "http://perladvent.org/2008/6/",
                add_modules => ['App::XLSperl'],
            },
            {
                name => '2008_12_08',
                summary => "Modules mentioned in Perl Advent Calendar 2008 (day 8)",
                url => "http://perladvent.org/2008/8/",
            },
            {
                name => '2008_12_10',
                summary => "Modules mentioned in Perl Advent Calendar 2008 (day 10)",
                url => "http://perladvent.org/2008/10/",
            },
            {
                name => '2008_12_11',
                summary => "Modules mentioned in Perl Advent Calendar 2008 (day 11)",
                url => "http://perladvent.org/2008/11/",
            },
            {
                name => '2008_12_12',
                summary => "Modules mentioned in Perl Advent Calendar 2008 (day 12)",
                url => "http://perladvent.org/2008/12/",
            },
            {
                name => '2008_12_13',
                summary => "Modules mentioned in Perl Advent Calendar 2008 (day 13)",
                url => "http://perladvent.org/2008/13/",
            },
            {
                name => '2008_12_14',
                summary => "Modules mentioned in Perl Advent Calendar 2008 (day 14)",
                url => "http://perladvent.org/2008/14/",
            },
            # module ForkBlock not published on CPAN
            #{
            #    name => '2008_12_15',
            #    summary => "Modules mentioned in Perl Advent Calendar 2008 (day 15)",
            #    url => "http://perladvent.org/2008/15/",
            #},
            {
                name => '2008_12_16',
                summary => "Modules mentioned in Perl Advent Calendar 2008 (day 16)",
                url => "http://perladvent.org/2008/16/",
            },
            {
                name => '2008_12_18',
                summary => "Modules mentioned in Perl Advent Calendar 2008 (day 18)",
                url => "http://perladvent.org/2008/18/",
            },
            {
                name => '2008_12_20',
                summary => "Modules mentioned in Perl Advent Calendar 2008 (day 20)",
                url => "http://perladvent.org/2008/20/",
            },
            {
                name => '2008_12_21',
                summary => "Modules mentioned in Perl Advent Calendar 2008 (day 21)",
                url => "http://perladvent.org/2008/21/",
                # typo in article App:Asciio
                add_modules => ['App::Asciio'],
            },
            {
                name => '2008_12_22',
                summary => "Modules mentioned in Perl Advent Calendar 2008 (day 22)",
                url => "http://perladvent.org/2008/22/",
            },
            {
                name => '2008_12_23',
                summary => "Modules mentioned in Perl Advent Calendar 2008 (day 23)",
                url => "http://perladvent.org/2008/23/",
            },
            {
                name => '2008_12_24',
                summary => "Modules mentioned in Perl Advent Calendar 2008 (day 24)",
                url => "http://perladvent.org/2008/24/",
            },
        ],
        namespace => 'Acme::CPANLists::Import::PerlAdvent',
        user_agent => 'Mozilla/5.0',
        dist_dir => "$Bin/..",
    },
    'app',
);

Perinci::CmdLine::Any->new(
    url => '/main/app',
    log => 1,
)->run;
